<?xml version="1.0"?>
<robot name="leg" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:macro name="leg" params="prefix suffix leg_y reflect">
 <link name="${prefix}_${suffix}_leg">
  <visual>
   <geometry>
    <box size="0.05 .05 ${leg}"/>
   </geometry>
   <origin rpy="0 0 0" xyz="0.0 0.0 ${leg/2}"/>
   <material name="white">
    <color rgba="1 1 1 1"/>
   </material>
  </visual>
 </link>
 <joint name="base_to_${prefix}_${suffix}_leg" type="fixed">
  <axis xyz="1 0 0"/>
  <origin rpy="0 3.1415 1.57075" xyz="0 ${leg_y*((width/2)+0.025)} 0"/>
  <parent link="${prefix}_axle"/>
  <child link="${prefix}_${suffix}_leg"/>
 </joint>

 <link name="${prefix}_${suffix}_lowleg">
  <visual>
   <geometry>
    <box size="0.04 .05 ${lowleg}"/>
   </geometry>
   <origin rpy="0 0 0" xyz="0.0 0.0 ${lowleg/2}"/>
   <material name="white"/>
  </visual>
 </link>
 <joint name="leg_to_${prefix}_${suffix}_lowleg" type="continuous">
  <axis xyz="${reflect} 0 0"/>
  <limit effort="1000.0" velocity="0.5"/>
  <origin rpy="0 0 0" xyz="${leg_y*-1*0.04} 0.0 ${leg}"/>
  <parent link="${prefix}_${suffix}_leg"/>
  <child link="${prefix}_${suffix}_lowleg"/>
  <mimic joint="base_to_${prefix}_axle" multiplier="1" offset="${leg_angle}"/> 
 </joint>

 <link name="${prefix}_${suffix}_turnleg">
  <visual>
   <geometry>
    <box size="0.02 .05 .05"/>
   </geometry>
   <origin rpy="0 0 0" xyz="0.0 0.0 0.025"/>
   <material name="blue"/>
  </visual>
 </link>
 <joint name="leg_to_${prefix}_${suffix}_turnleg" type="revolute">
  <axis xyz="0 0 1"/>
  <limit effort="1000.0" lower="-3.1415" upper="3.1415" velocity="0.5"/>
  <origin rpy="0 0 0" xyz="0.0 0.0 ${lowleg}"/>
  <parent link="${prefix}_${suffix}_lowleg"/>
  <child link="${prefix}_${suffix}_turnleg"/>
 </joint>

 <link name="${prefix}_${suffix}_wheel">
    <visual>
      <geometry>
        <mesh filename="package://train/urdf/meshes/hjul.stl" />
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="${prefix}_${suffix}_turnleg"/>
    <child link="${prefix}_${suffix}_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 0 0.05"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>
</xacro:macro>
</robot>
